import type { Metadata } from 'next'
import Link from 'next/link'
import { HomeFooter, HomeHeader, PhoneIcon, ServiceSidebar, WhatsAppIcon } from '@/components/gov-shell'
import { LeadForm } from '@/components/screening/lead-form'
import { site, phoneHref, whatsappHref } from '@/lib/site'
export const metadata:Metadata={title:'הוצאת רישיון נשק פרטי',description:site.description}
const benefits=[['01','בדיקה ראשונית','בודקים אם יש טעם להתקדם ומה נכון לבדוק כבר בתחילת הדרך, כולל עמידה בתנאי הסף הנדרשים.',true],['02','סדר במסמכים','מבינים אילו מסמכים עשויים להיות רלוונטיים ואיך להתארגן נכון כדי למנוע דחיות ועיכובים מיותרים.',false],['03','מיקוד בתהליך','מקבלים תמונה מסודרת של השלבים האפשריים במקום לפעול בחוסר ודאות מול המערכת הבירוקרטית.',false],['04','תצהיר כשנדרש','אם בהמשך עולה צורך בתצהיר משפטי חתום, ניתן להשלים אותו במהירות ובאופן מסודר מול עורך דין.',true]] as const
const faqs=[['איך השירות עובד?','עונים על 5 שאלות קצרות, מקבלים אינדיקציה ראשונית ולאחר מכן ממשיכים לשיחה אישית עם עורך דין. הבדיקה אינה מחליפה החלטה רשמית של הרשות.'],['מי יכול להגיש בקשה?','מי שעומד בתנאי הסף ובאחד התבחינים הקבועים בדין יכול לשקול הגשת בקשה. הבדיקה באתר נועדה למקד את הבירור הראשוני.'],['אילו מסמכים עשויים להידרש?','המסמכים משתנים לפי התבחין והנסיבות. במסגרת השירות נסביר אילו אישורים ומסמכים רלוונטיים למקרה שלכם.'],['מה קורה לאחר הבדיקה הראשונית?','ניתן לפנות ישירות בוואטסאפ או בטלפון ולהמשיך לבדיקה פרטנית בהתאם לצורך.']] as const
export default function HomePage(){return <div className="home-final"><HomeHeader/><main id="main" className="home-layout"><ServiceSidebar/><div className="home-content-final"><section className="home-hero-final"><h1>הוצאת רישיון נשק פרטי</h1><h2>בדיקה ראשונית והכוונה של עורך דין לאורך שלבי התהליך</h2><i className="hero-rule"/><p>השירות מיועד למי ששוקל להגיש בקשה לרישיון נשק פרטי ורוצה להבין בצורה מסודרת מה נדרש, אילו שלבים צפויים בהמשך, ומתי יש צורך בתצהיר או בבדיקה משפטית נוספת.</p><Link className="home-primary" href="/check">התחילו בדיקה ראשונית</Link></section><div className="info-banner-final"><span>הבדיקה הראשונית באתר ללא עלות. המשך ליווי, ככל שיידרש, יתומחר ויסוכם מראש.</span><b className="info-dot">i</b></div><section id="included" className="benefits-final"><header className="section-head-final"><h2>מה מקבלים בפועל?</h2><p>בדיקה ראשונית, סדר בתהליך והכוונה ברורה להמשך.</p></header><div className="benefits-grid-final">{benefits.map(([n,t,b,p])=><article className={`benefit-final${p?' primary':''}`} key={n}><div className="benefit-head-final"><span className="num">{n}</span><h3>{t}</h3></div><hr/><p>{b}</p></article>)}</div></section><section id="faq" className="faq-final"><header className="faq-title-final"><h2>שאלות נפוצות</h2><i/></header><div className="faq-stack-final">{faqs.map(([q,a],i)=><details className="faq-item-final" key={q} open={i===0}><summary><img className="faq-chev" src="/figma/chevron-down-14.svg" alt=""/><span>{q}</span></summary><div className="faq-answer-final">{a}</div></details>)}</div></section><section id="contact" className="lawyer-callback-final"><header className="lawyer-head-final"><h2>ליווי אישי של עורך דין</h2><p>מקצועיות, סדר והכוונה משפטית לאורך שלבי הבקשה</p></header><div className="lawyer-body-final"><p>לאחר הבדיקה הראשונית אפשר להמשיך לשירות אישי עם עורך דין, שיסביר את המסלול האפשרי, את המסמכים והשלבים הרלוונטיים, וילווה את הטיפול לפי הצורך.</p><div className="contact-split-final"><div className="direct-buttons-final"><Link className="rfl-btn home-primary" href="/check">התחילו בדיקה ראשונית</Link><a className="rfl-btn rfl-whatsapp" href={whatsappHref()} target="_blank" rel="noreferrer"><span>וואטסאפ</span><WhatsAppIcon/></a><a className="rfl-btn rfl-call" href={phoneHref()}><span>התקשרו עכשיו</span><PhoneIcon/></a></div><div className="contact-label-final"><h3>צרו קשר ישיר:</h3><p>מענה מהיר ומקצועי על ידי צוות המשרד</p><span className="trust-pill">עמידה קפדנית בכל דרישות החוק</span></div></div></div><div className="callback-wrap-final"><LeadForm variant="home"/></div></section></div></main><HomeFooter/></div>}
